apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emotion-ingress-https
  namespace: emotion-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    kubernetes.io/ingress.class: gce
spec:
  tls:
  - hosts:
    - emotion-detection.duckdns.org
    secretName: emotion-tls-cert
  rules:
  - host: emotion-detection.duckdns.org
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: emotion-frontend-service
            port:
              number: 80
